//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTB
    {
        public decimal AT_ID { get; set; }
        public string Asset_ID { get; set; }
        public string Asset_Name { get; set; }
        public string Model_No { get; set; }
        public string Serial_No { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<int> Cur_ID { get; set; }
        public Nullable<System.DateTime> Purchase_DT { get; set; }
        public string Asset_Categoty { get; set; }
        public string Dept { get; set; }
        public string Manager_Name { get; set; }
        public Nullable<System.DateTime> Warranty_DT { get; set; }
        public string WarrantyMonth { get; set; }
        public Nullable<System.DateTime> Next_mantain_DT { get; set; }
        public string Supplaier_Name { get; set; }
        public string Supplier_Phone { get; set; }
        public byte[] Warranty_File { get; set; }
        public string FilePath { get; set; }
        public string Extension { get; set; }
        public string Warranty_File_Name { get; set; }
        public string Asset_Note { get; set; }
        public byte[] Asset_Image { get; set; }
        public string CreatedBY { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
