//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_CategoryTB
    {
        public decimal AS_CAT_ID { get; set; }
        public string CAT_ID { get; set; }
        public string Cat_Name { get; set; }
        public Nullable<int> LI_Type { get; set; }
        public string Cat_Des { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreatedByW { get; set; }
    }
}
