//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_DisposalTB
    {
        public decimal DIT_ID { get; set; }
        public string Disposal_ID { get; set; }
        public string AssetID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string AssetName { get; set; }
        public Nullable<System.DateTime> PurchaseDT { get; set; }
        public Nullable<decimal> PurchaseAMT { get; set; }
        public Nullable<decimal> DepreciationM { get; set; }
        public Nullable<decimal> Total_Depreciation { get; set; }
        public Nullable<System.DateTime> DisposalDT { get; set; }
        public string MarkAS { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
