//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTB
    {
        public decimal ATT_ID { get; set; }
        public string Atten_No { get; set; }
        public string EmplID { get; set; }
        public string FullName1 { get; set; }
        public Nullable<System.DateTime> ATT_Date { get; set; }
        public Nullable<decimal> Present { get; set; }
        public Nullable<decimal> Adsent { get; set; }
        public Nullable<decimal> Excuse { get; set; }
        public Nullable<System.DateTime> DateCreatedDT { get; set; }
        public string CreatedByEmpl { get; set; }
    }
}
