//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusTB
    {
        public decimal BT_ID { get; set; }
        public string Bonus_ID { get; set; }
        public string Sal_Grade_Code2 { get; set; }
        public string Bonus_Name { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreatedBY { get; set; }
    }
}
