//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellTB
    {
        public decimal CT_ID { get; set; }
        public string Cell_ID { get; set; }
        public string Cell_Name { get; set; }
        public string Cell_Lead_Name { get; set; }
        public string Cell_Asst_Name { get; set; }
        public string Cell_Adress { get; set; }
        public string Cell_Location { get; set; }
        public string Zonal_Name { get; set; }
        public string Cell_Email { get; set; }
        public string Cell_Phone { get; set; }
        public string Cell_Status { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreatedBy { get; set; }
    }
}
