//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectCardTB
    {
        public decimal CD_ID { get; set; }
        public string ConCard_NO { get; set; }
        public string Sname { get; set; }
        public string OName { get; set; }
        public string Fullname_Guest { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Contact_No { get; set; }
        public string King_Of_Service { get; set; }
        public string WishTo { get; set; }
        public string HearAt_US1 { get; set; }
        public string HearAt_US2 { get; set; }
        public string HearAt_US3 { get; set; }
        public string HearAt_US4 { get; set; }
        public string Interested_IN1 { get; set; }
        public string Interested_IN2 { get; set; }
        public string Interested_IN3 { get; set; }
        public string Interested_IN4 { get; set; }
        public string Interested_IN5 { get; set; }
        public string Prayer_Rq { get; set; }
        public string InvitedBY { get; set; }
        public string Member_ID { get; set; }
        public string CreatedBY { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
