//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyTB
    {
        public decimal CT_ID { get; set; }
        public string CUR_NAME { get; set; }
        public string CUR_SHORT_NAME { get; set; }
        public string Cur_Symbol { get; set; }
        public Nullable<int> Cur_ID { get; set; }
        public string CreatedBy { get; set; }
    }
}
