//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTB
    {
        public decimal DT_ID { get; set; }
        public string Dept_ID { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_ManagerName { get; set; }
        public Nullable<decimal> No_of_Unit { get; set; }
        public string Dept_Units1 { get; set; }
        public string Dept_Units2 { get; set; }
        public string Dept_Units3 { get; set; }
        public string Dept_Units4 { get; set; }
        public string Dept_Units5 { get; set; }
        public string Dept_Units6 { get; set; }
        public string Dept_Units7 { get; set; }
        public string Dept_Units8 { get; set; }
        public string Dept_Units9 { get; set; }
        public string Dept_Units10 { get; set; }
        public string Dept_Units11 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
