//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense_CartTB
    {
        public decimal EXP_Cart_NO { get; set; }
        public string EXP_Cart_Row_No { get; set; }
        public string EXP_Cart_Batch_No { get; set; }
        public string EXP_Cart_Exp_Cat { get; set; }
        public string EXP_Cart_Pro_Name { get; set; }
        public Nullable<decimal> EXP_Cart_Unit_Price { get; set; }
        public Nullable<int> EXP_Cur_ID { get; set; }
        public Nullable<decimal> EXP_Cart_Quantity { get; set; }
        public Nullable<decimal> EXP_Cart_TotalPrice { get; set; }
    }
}
