//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseTB
    {
        public decimal EXP_NO { get; set; }
        public string Exp_BatchNO { get; set; }
        public string Exp_Dept_Name { get; set; }
        public string Exp_Cash_Mode { get; set; }
        public string Exp_Chq_No { get; set; }
        public string Exp_eTran_No { get; set; }
        public Nullable<decimal> Exp_Batch_Total { get; set; }
        public Nullable<int> Exp_Cur_ID { get; set; }
        public string Exp_CreatedBY { get; set; }
        public Nullable<System.DateTime> Exp_Create_DT { get; set; }
    }
}
