//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamTB
    {
        public decimal FT_ID { get; set; }
        public string Fam_ID { get; set; }
        public string Fam_Name { get; set; }
        public string Fam_Greetings { get; set; }
        public string Husb_Name { get; set; }
        public string Wife_Name { get; set; }
        public Nullable<decimal> No_Of_Child { get; set; }
        public string Name_Of_Child1 { get; set; }
        public string Name_Of_Child2 { get; set; }
        public string Name_Of_Child3 { get; set; }
        public string Name_Of_Child4 { get; set; }
        public string Name_Of_Child5 { get; set; }
        public string Name_Of_Child6 { get; set; }
        public byte[] Fam_Pic { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Home_Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreatedBy { get; set; }
    }
}
