//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class First_FruitTB
    {
        public decimal FF_ID { get; set; }
        public string FF_NO { get; set; }
        public string FF_Mem_ID { get; set; }
        public string FF_Mem_Name { get; set; }
        public string FF_Mem_Phone { get; set; }
        public string FF_Mem_Cell { get; set; }
        public string FF_Pay_Channel { get; set; }
        public string FF_Chq_No { get; set; }
        public string FF_eTran_No { get; set; }
        public string FF_Cur_Type { get; set; }
        public Nullable<int> FF_Cur_ID { get; set; }
        public string FF_Cur_Symbol { get; set; }
        public Nullable<decimal> FF_Amount { get; set; }
        public Nullable<System.DateTime> FF_CreateDT { get; set; }
        public string FF_CreatedBy { get; set; }
    }
}
