//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_CategoryTB
    {
        public decimal GE_CAT_NO { get; set; }
        public string GE_CAT_ID { get; set; }
        public string GE_Cat_Name { get; set; }
        public string GE_Cat_Des { get; set; }
        public Nullable<int> GE_Liability_Type { get; set; }
        public Nullable<System.DateTime> GE_CreateDT { get; set; }
        public string GE_CreatedBy { get; set; }
    }
}
