//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Deposit
    {
        public decimal Tran_ID { get; set; }
        public string DepositID { get; set; }
        public Nullable<decimal> GL_AcctNo { get; set; }
        public string Depo_GL_Name { get; set; }
        public Nullable<decimal> GL_Acct_Bal { get; set; }
        public string Cur_Symbol { get; set; }
        public string Cur_Descr { get; set; }
        public string GL_Type { get; set; }
        public string Mode { get; set; }
        public string Chq_No { get; set; }
        public Nullable<decimal> Deposit_Amt { get; set; }
        public Nullable<System.DateTime> createDT { get; set; }
        public string Description { get; set; }
        public string depositedBy { get; set; }
    }
}
