//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Master_History
    {
        public decimal GMH_ID { get; set; }
        public decimal GMH_GMH_Acct_no { get; set; }
        public string GMH_Acct_type { get; set; }
        public string GMH_Member_ID { get; set; }
        public string GMH_Description { get; set; }
        public System.DateTime GMH_Create_dt { get; set; }
        public System.DateTime GMH_Effective_dt { get; set; }
        public Nullable<decimal> GMH_Prev_Balance { get; set; }
        public Nullable<decimal> GMH_Amt { get; set; }
        public Nullable<decimal> GMH_Total_Balance { get; set; }
        public Nullable<short> GMH_Debit_credit { get; set; }
        public string GMH_Empl_id { get; set; }
        public int GMH_Cur_ID { get; set; }
    }
}
