//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Master
    {
        public decimal IL_ID { get; set; }
        public Nullable<decimal> IL_NO { get; set; }
        public string IL_Type { get; set; }
        public Nullable<decimal> IL_Bal { get; set; }
        public string IL_Name { get; set; }
        public string IL_Cur_Short_Code { get; set; }
        public string IL_Description { get; set; }
        public Nullable<int> IL_Cur_ID { get; set; }
        public string IL_Cur_Symbol { get; set; }
        public Nullable<System.DateTime> IL_GLS_CreateDT { get; set; }
        public string IL_GLS_CreatedBY { get; set; }
    }
}
