//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Setup
    {
        public decimal GT_ID { get; set; }
        public Nullable<decimal> GL_NO { get; set; }
        public string GL_Type { get; set; }
        public Nullable<decimal> Cur_Bal { get; set; }
        public string GL_Name { get; set; }
        public string Cur_Short_Code { get; set; }
        public string Cur_Description { get; set; }
        public Nullable<int> Cur_ID { get; set; }
        public string Cur_Symbol { get; set; }
        public Nullable<System.DateTime> GLS_CreateDT { get; set; }
        public string GLS_CreatedBY { get; set; }
    }
}
