//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Transactions
    {
        public decimal Tran_ID { get; set; }
        public decimal Acct_no { get; set; }
        public string Acct_type { get; set; }
        public string Member_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Create_dt { get; set; }
        public System.DateTime Effective_dt { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<short> Debit_credit { get; set; }
        public string Empl_id { get; set; }
        public int Cur_ID { get; set; }
    }
}
