//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invited_GuestTB
    {
        public int IV_TD { get; set; }
        public string Name_of_Guest { get; set; }
        public string Name_of_Who_InviteedGuest { get; set; }
        public string TKC_MemID { get; set; }
        public Nullable<decimal> Ivite_Count { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
