//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeeperDBEntities : DbContext
    {
        public KeeperDBEntities()
            : base("name=KeeperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset_CategoryTB> Asset_CategoryTB { get; set; }
        public virtual DbSet<Asset_DisposalTB> Asset_DisposalTB { get; set; }
        public virtual DbSet<AssetTB> AssetTBs { get; set; }
        public virtual DbSet<AttendanceTB> AttendanceTBs { get; set; }
        public virtual DbSet<BonusTB> BonusTBs { get; set; }
        public virtual DbSet<CellTB> CellTBs { get; set; }
        public virtual DbSet<ConnectCardTB> ConnectCardTBs { get; set; }
        public virtual DbSet<CurrencyTB> CurrencyTBs { get; set; }
        public virtual DbSet<DepartmentTB> DepartmentTBs { get; set; }
        public virtual DbSet<Expense_CartTB> Expense_CartTB { get; set; }
        public virtual DbSet<ExpenseTB> ExpenseTBs { get; set; }
        public virtual DbSet<FamTB> FamTBs { get; set; }
        public virtual DbSet<First_FruitTB> First_FruitTB { get; set; }
        public virtual DbSet<GE_CategoryTB> GE_CategoryTB { get; set; }
        public virtual DbSet<GL_Deposit> GL_Deposit { get; set; }
        public virtual DbSet<GL_Master> GL_Master { get; set; }
        public virtual DbSet<GL_Master_History> GL_Master_History { get; set; }
        public virtual DbSet<GL_Setup> GL_Setup { get; set; }
        public virtual DbSet<GL_Transactions> GL_Transactions { get; set; }
        public virtual DbSet<Invited_GuestTB> Invited_GuestTB { get; set; }
        public virtual DbSet<LiabilitiesTB> LiabilitiesTBs { get; set; }
        public virtual DbSet<LoanTB> LoanTBs { get; set; }
        public virtual DbSet<ManagersTB> ManagersTBs { get; set; }
        public virtual DbSet<MembTB> MembTBs { get; set; }
        public virtual DbSet<MoneyBlockTB> MoneyBlockTBs { get; set; }
        public virtual DbSet<OfferingTB> OfferingTBs { get; set; }
        public virtual DbSet<PledgeTB> PledgeTBs { get; set; }
        public virtual DbSet<PWDC_WCompleteTB> PWDC_WCompleteTB { get; set; }
        public virtual DbSet<PWDR_ManageTB> PWDR_ManageTB { get; set; }
        public virtual DbSet<Sal_GradeTB> Sal_GradeTB { get; set; }
        public virtual DbSet<Sal_PaymentTB> Sal_PaymentTB { get; set; }
        public virtual DbSet<Salary_UserTB> Salary_UserTB { get; set; }
        public virtual DbSet<ServiceOfferingTB> ServiceOfferingTBs { get; set; }
        public virtual DbSet<ServiceTB> ServiceTBs { get; set; }
        public virtual DbSet<TitheTB> TitheTBs { get; set; }
        public virtual DbSet<TransactionCodeTB> TransactionCodeTBs { get; set; }
        public virtual DbSet<UserTB> UserTBs { get; set; }
        public virtual DbSet<ZoneTB> ZoneTBs { get; set; }
    }
}
