//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiabilitiesTB
    {
        public decimal LI_NO { get; set; }
        public string LI_ID { get; set; }
        public string LI_Name { get; set; }
        public string LI_Des { get; set; }
        public Nullable<int> LI_Type { get; set; }
        public Nullable<System.DateTime> LI_CreateDT { get; set; }
        public string LI_CreatedBy { get; set; }
    }
}
