//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTB
    {
        public decimal LT_ID { get; set; }
        public string Loan_NO { get; set; }
        public string LPay_No { get; set; }
        public string Member_ID { get; set; }
        public string Sal_Grade_Code { get; set; }
        public string FullName { get; set; }
        public string PhoneNoR { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<System.DateTime> Create_LDT { get; set; }
        public string CreatedLBy { get; set; }
        public string LoanPurpose { get; set; }
        public Nullable<System.DateTime> LoanNeededDT { get; set; }
        public Nullable<decimal> MonthlyDeduct { get; set; }
        public string EmailADD { get; set; }
    }
}
