//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembTB
    {
        public decimal MT_ID { get; set; }
        public string Fam_Name { get; set; }
        public string TKC_MemID { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Sname { get; set; }
        public string Lname { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Emegency_Contact { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Zip { get; set; }
        public byte[] Picture { get; set; }
        public string Mari_Status { get; set; }
        public string Fam_Role { get; set; }
        public string Official_Capa { get; set; }
        public Nullable<System.DateTime> JoinDT { get; set; }
        public string Is_Baptised { get; set; }
        public Nullable<System.DateTime> BaptismDT { get; set; }
        public string Service_Name { get; set; }
        public string Cell_Name { get; set; }
        public string JobTitile { get; set; }
        public string Company_Name { get; set; }
        public string Dept { get; set; }
        public string Member_Status { get; set; }
        public string CreatedBY { get; set; }
    }
}
