//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyBlockTB
    {
        public decimal MB_TD { get; set; }
        public Nullable<decimal> MB_GL_NO { get; set; }
        public string MB_Descript { get; set; }
        public string MB_Cur_Sign { get; set; }
        public Nullable<decimal> MB_Bal { get; set; }
        public Nullable<System.DateTime> MB_CreateDT { get; set; }
        public string MB_CreatedBy { get; set; }
    }
}
