//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferingTB
    {
        public decimal OT_ID { get; set; }
        public string Pay_ID { get; set; }
        public string TKC_MemID { get; set; }
        public Nullable<System.DateTime> PaymentDT { get; set; }
        public string Payment_Channel { get; set; }
        public string Cheque_NO { get; set; }
        public string Fund_Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Mem_Fullname { get; set; }
        public Nullable<decimal> GL_No { get; set; }
        public string CreatedBY { get; set; }
    }
}
