//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PledgeTB
    {
        public decimal PP_NO { get; set; }
        public string PP_ID { get; set; }
        public string PP_Mem_ID { get; set; }
        public string PP_Mem_Name { get; set; }
        public string PP_Mem_Phone { get; set; }
        public string PP_Mem_Cell { get; set; }
        public string PP_Pay_Channel { get; set; }
        public string PP_Chq_No { get; set; }
        public string PP_eTran_No { get; set; }
        public string PP_Cur_Type { get; set; }
        public Nullable<int> PP_CurID { get; set; }
        public string PP_Cur_Symbol { get; set; }
        public string PP_iSMember { get; set; }
        public string PP_Address { get; set; }
        public Nullable<decimal> PP_Amount { get; set; }
        public Nullable<System.DateTime> PP_CreateDT { get; set; }
        public string PP_CreatedBy { get; set; }
    }
}
