//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWDC_WCompleteTB
    {
        public decimal PWDC_ID { get; set; }
        public string TKHS_ID { get; set; }
        public string ResetType { get; set; }
        public string Username { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> ReqDT { get; set; }
        public string Platform { get; set; }
        public Nullable<decimal> complete { get; set; }
    }
}
