//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWDR_ManageTB
    {
        public decimal PWDR_ID { get; set; }
        public string TKHS_ID { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string platformTB { get; set; }
        public Nullable<System.DateTime> requestDT { get; set; }
        public Nullable<System.DateTime> PWD_ResetDT { get; set; }
        public string creatBY { get; set; }
        public string Request_Type { get; set; }
    }
}
