//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_PaymentTB
    {
        public decimal STP_ID { get; set; }
        public string Pay_Slip_No { get; set; }
        public string Pay_Acct_No { get; set; }
        public string Name_Of_Member { get; set; }
        public string MembershipID { get; set; }
        public string SalGrade { get; set; }
        public Nullable<decimal> BaseAmt { get; set; }
        public Nullable<decimal> MonthBonus { get; set; }
        public Nullable<decimal> LoanDedt { get; set; }
        public Nullable<decimal> Mark_Present { get; set; }
        public Nullable<decimal> Mark_Absent { get; set; }
        public Nullable<decimal> Mark_Excuse { get; set; }
        public Nullable<decimal> NetSal { get; set; }
        public Nullable<System.DateTime> CreateSDT { get; set; }
        public string CreatedSBY { get; set; }
    }
}
