//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_GradeTB
    {
        public decimal SGT_ID { get; set; }
        public string Grade_ID { get; set; }
        public string Grade_Name { get; set; }
        public string Grade_Code { get; set; }
        public Nullable<decimal> Base_Amt { get; set; }
        public Nullable<decimal> OT_Per { get; set; }
        public Nullable<decimal> Perf_Bonus { get; set; }
        public Nullable<System.DateTime> CreateDATE { get; set; }
        public string CreatedBY_Who { get; set; }
    }
}
