//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOfferingTB
    {
        public decimal OR_NO { get; set; }
        public string OR_ID { get; set; }
        public string Service_Type { get; set; }
        public Nullable<decimal> MW_Offering { get; set; }
        public Nullable<decimal> MF_Offering { get; set; }
        public Nullable<decimal> SF_Offering { get; set; }
        public Nullable<decimal> SS_Offering { get; set; }
        public Nullable<System.DateTime> RO_CreateDT { get; set; }
        public string RO_CreatedBY { get; set; }
    }
}
