//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTB
    {
        public decimal SR_ID { get; set; }
        public string Service_ID { get; set; }
        public string Service_Name { get; set; }
        public System.TimeSpan Service_Start_Time { get; set; }
        public Nullable<System.TimeSpan> Service_End_Time { get; set; }
        public string Service_Lead_Pastor { get; set; }
        public string Service_Assist_Pastor { get; set; }
        public System.DateTime Create_DT { get; set; }
        public string CreatedBy { get; set; }
    }
}
