//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitheTB
    {
        public decimal TI_ID { get; set; }
        public string Tithe_ID { get; set; }
        public string T_Mem_ID { get; set; }
        public string T_Mem_Name { get; set; }
        public string T_Mem_Phone { get; set; }
        public string T_Mem_Cell { get; set; }
        public string T_Pay_Channel { get; set; }
        public string T_Chq_No { get; set; }
        public string T_eTran_No { get; set; }
        public string T_Cur_Type { get; set; }
        public string T_Cur_Symbol { get; set; }
        public Nullable<int> T_CurID { get; set; }
        public Nullable<decimal> T_Amount { get; set; }
        public string T_Description { get; set; }
        public Nullable<System.DateTime> T_Paid_DT { get; set; }
        public Nullable<System.DateTime> T_CreateDT { get; set; }
        public string T_CreatedBy { get; set; }
    }
}
