//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCodeTB
    {
        public decimal TC_ID { get; set; }
        public Nullable<decimal> Tran_Code { get; set; }
        public string TranCode_Descrip { get; set; }
        public string Asso_Cur_Symbol { get; set; }
        public string CreatedBY { get; set; }
        public Nullable<System.DateTime> CreatDT { get; set; }
    }
}
