//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTB
    {
        public decimal UT_ID { get; set; }
        public string TKHS_ID { get; set; }
        public string Title { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string Zip_code { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Marrital_Status { get; set; }
        public string NOK_Name { get; set; }
        public string NOK_Phone { get; set; }
        public string NOK_Address { get; set; }
        public string NOKRela { get; set; }
        public string UserFam { get; set; }
        public string Dep { get; set; }
        public string SysRoll { get; set; }
        public Nullable<System.DateTime> Create_dt { get; set; }
        public Nullable<System.DateTime> JDate { get; set; }
        public string Member_Status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte[] Picture { get; set; }
        public string Security_question1 { get; set; }
        public string Security_question2 { get; set; }
        public string Security_question3 { get; set; }
        public string Secu_quest_answer1 { get; set; }
        public string Secu_quest_answer2 { get; set; }
        public string Secu_quest_answer3 { get; set; }
        public Nullable<decimal> Pwd_lock { get; set; }
        public string CreatedBy { get; set; }
        public string Admin_loc { get; set; }
        public string OfficialCapacity { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> securitySet { get; set; }
    }
}
