//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneTB
    {
        public decimal ZT_ID { get; set; }
        public string Zone_ID { get; set; }
        public string Zone_Name { get; set; }
        public string Zone_Lead_Name { get; set; }
        public string Zone_Asst_Name { get; set; }
        public string Zonel_Adress { get; set; }
        public string Zone_Location { get; set; }
        public string Zone_Email { get; set; }
        public string Zone_Phone { get; set; }
        public string Zone_Status { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreatedBy { get; set; }
    }
}
